### ISSUE TITLE
Procura usar variables sobre llamadas en los metodos

### ISSUE THREAD

**Issue by CRAG666** [nayaxolotl/Nayeli_Gissel_Larios_Perez_objeto_seguro#1]
``` python
    Obj1 = ObjetoSeguro("Obj1")
    Obj2 = ObjetoSeguro("Obj2")
    Obj2.saludar(Obj2.nombre,Obj2.cifrar_msj(Obj1.llave_publica(), "Hola Mundo"))
    Obj2.almacenar_msj("Hola mundo")
    Obj2.almacenar_msj("Segundo mensaje")
    Obj2.almacenar_msj("Tercer mensaje")
    Obj2.consultar_msj(0)
```
en el caso de saludar, podrias utilizar variables para almacenar la salida del mensaje cifrado
>  son el nombre del objeto que comienza la comunicación y el mensaje cifrado con la llave pública del destinatario.

por otro lado en el caso particular de esperar respuesta es es solo capturar el retorno de responder es decir en la parte final de tu codigo debes incluir un return self.responder(msg)
entonces:

``` python
respuesta = Obj2.saludar(Obj2.nombre,Obj2.cifrar_msj(Obj1.llave_publica(), "Hola Mundo"))
Obj1.esperar_respuesta(respuesta)
```

**Comment by CRAG666** [comment]
@nayaxolotl puedes cerrar la issue si esto te ayudo a resolver tu problema y de caso contrario puedes preguntar alguna otra cosa mas en esta issue

**Comment by nayaxolotl** [comment]
Si profe @CRAG666 , creo que ya le entendí y ya lo resolví.
Gracias
